#!/usr/bin/env bash
# deploy.sh - one-shot deploy of the signl Kalshi trading bot into a NemoClaw sandbox.
#
# Usage:   bash deploy.sh [sandbox-name]
# Default sandbox name: signl3
#
# Steps:
#   1. Stage Python modules + RSA PEM + signl.env into the skill directory.
#   2. Run host-side `kalshi_client verify` to confirm credentials work.
#   3. Apply the kalshi network/fs policy preset to the sandbox.
#   4. Install the skill (uploads /sandbox/.openclaw/skills/kalshi-trader/).
#   5. `pip install -r requirements.txt` inside the sandbox.
#   6. Recover the Telegram bridge.
#   7. Print a checklist of Telegram messages to try.

set -euo pipefail

SANDBOX="${1:-signl3}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE="$ROOT/sandbox/workspace"
SKILL_DIR="$ROOT/sandbox/skills/kalshi-trader"
POLICY="$ROOT/policies/kalshi.yaml"
ENV_FILE="$ROOT/.env"
PEM_HOST="$ROOT/kalshi-rsa-private.pem"

step() { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
fail() { printf '\n\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ -f "$ENV_FILE" ]] || fail "missing $ENV_FILE - copy .env.example and fill it in"
[[ -f "$PEM_HOST" ]] || fail "missing $PEM_HOST (your Kalshi RSA private key)"
[[ -f "$POLICY"   ]] || fail "missing $POLICY"
[[ -d "$WORKSPACE" ]] || fail "missing workspace dir at $WORKSPACE"
[[ -d "$SKILL_DIR" ]] || fail "missing skill dir at $SKILL_DIR"
command -v nemoclaw >/dev/null || fail "nemoclaw CLI not on PATH"

step "Loading credentials from $ENV_FILE"
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a
: "${KALSHI_API_KEY_ID:?KALSHI_API_KEY_ID not set in .env}"
: "${TELEGRAM_BOT_TOKEN:?TELEGRAM_BOT_TOKEN not set in .env}"
: "${NVIDIA_API_KEY:?NVIDIA_API_KEY not set in .env}"
: "${BRAVE_API_KEY:?BRAVE_API_KEY not set in .env}"

step "Staging Python modules into $SKILL_DIR/"
cp "$WORKSPACE"/db.py            "$SKILL_DIR/db.py"
cp "$WORKSPACE"/kalshi_client.py "$SKILL_DIR/kalshi_client.py"
cp "$WORKSPACE"/risk.py          "$SKILL_DIR/risk.py"
cp "$WORKSPACE"/sentiment.py     "$SKILL_DIR/sentiment.py"
cp "$WORKSPACE"/scanner.py       "$SKILL_DIR/scanner.py"
cp "$WORKSPACE"/watchlist.py     "$SKILL_DIR/watchlist.py"
cp "$ROOT/requirements.txt"      "$SKILL_DIR/requirements.txt"

step "Staging RSA private key into $SKILL_DIR/kalshi-rsa-private.pem"
cp "$PEM_HOST" "$SKILL_DIR/kalshi-rsa-private.pem"
chmod 600 "$SKILL_DIR/kalshi-rsa-private.pem"

step "Writing $SKILL_DIR/signl.env (sourced by every Python invocation)"
cat > "$SKILL_DIR/signl.env" <<EOF
# Auto-generated by deploy.sh - do not commit.
KALSHI_API_KEY_ID=$KALSHI_API_KEY_ID
KALSHI_PRIVATE_KEY_PATH=/sandbox/.openclaw/skills/kalshi-trader/kalshi-rsa-private.pem
${KALSHI_PRIVATE_KEY_PASSWORD:+KALSHI_PRIVATE_KEY_PASSWORD=$KALSHI_PRIVATE_KEY_PASSWORD}
${KALSHI_BASE_URL:+KALSHI_BASE_URL=$KALSHI_BASE_URL}
NVIDIA_API_KEY=$NVIDIA_API_KEY
BRAVE_API_KEY=$BRAVE_API_KEY
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
EOF
chmod 600 "$SKILL_DIR/signl.env"

step "Host-side smoke test: python3 -m kalshi_client verify"
( cd "$WORKSPACE" && python3 -m kalshi_client verify )

step "Applying network policy preset to '$SANDBOX'"
nemoclaw "$SANDBOX" policy-add --from-file "$POLICY" --yes \
  || echo "(policy-add exited non-zero; may already be applied)"

step "Installing skill into '$SANDBOX'"
nemoclaw "$SANDBOX" skill install "$SKILL_DIR"

step "Installing Python deps inside '$SANDBOX' (PEP 668 -> --break-system-packages)"
# Pipe a single-line bash script into the sandbox SSH. Bound by `timeout`
# because `nemoclaw connect` doesn't always close cleanly after stdin EOF.
REMOTE_CMD='cd /sandbox/.openclaw/skills/kalshi-trader && \
  set -a && . ./signl.env && set +a && \
  python3 -m pip install --quiet --break-system-packages -r requirements.txt && \
  python3 -c "import db, kalshi_client, risk, sentiment, scanner, watchlist; print(\"imports OK\")" && \
  python3 -m kalshi_client verify && \
  echo "deps OK"'
timeout --foreground 120s bash -c \
  "echo '$REMOTE_CMD' | nemoclaw '$SANDBOX' connect" \
  || echo "(remote bootstrap returned non-zero or hit timeout; check output above)"

step "Recovering the Telegram bridge"
nemoclaw "$SANDBOX" recover || true

cat <<'BANNER'

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  signl deployed.

  From Telegram, message your bot:

    help
    balance
    watchlist
    add KXMARKET manual
    analyze KXMARKET
    scan

  Watch sandbox logs in another terminal:

    nemoclaw signl3 logs --follow

  To re-deploy after editing the host workspace, just run this script again.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BANNER
